---
# Source: upro-channel/templates/22-deployable-interest.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: upro-deployable-deployment-interest
  namespace: upro-icam-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: upro-application
    subapp: interest
spec:
  template:
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: upro-interest
      namespace: upro-icam-app-ns
      labels:
        app: upro-application
        subname: interest     
    spec:
      selector:
        matchLabels:
          app: upro-application
          subname: interest
      replicas: 1
      template:
        metadata:
          labels:
            app: upro-application
            subname: interest          
        spec:
          containers:
            - name: container-interest
              image: "gandhicloudlab/upro-interest-icam-130-2:latest"
              imagePullPolicy: Always
              ports:
                - name: my-http
                  containerPort: 9032
                  protocol: TCP
                - name: https
                  containerPort: 8084
              env:
                - name: OPENTRACING_ENABLED
                  value: "true"
                - name: JAEGER_SAMPLER_TYPE
                  value: probabilistic
                - name: JAEGER_SAMPLER_PARAM
                  value: "1"
                - name: LATENCY_SAMPLER_PARAM
                  value: "1"
              volumeMounts:
                - name: global-environment
                  mountPath: /opt/ibm/apm/serverconfig   
          volumes:
            - name: global-environment
              secret:
                secretName: icam-server-secret      
                optional: true        
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: upro-deployable-service-interest
  namespace: upro-icam-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: upro-application
    subapp: interest
spec:
  template:
    kind: Service
    apiVersion: v1
    metadata:
      name: upro-interest
      namespace: upro-icam-app-ns
      labels:
        app: upro-application
        subname: interest
      # annotations:
        # mcm.ibm.com/service-discovery: "{}"            
    spec:
      type: NodePort
      ports:
      - name: my-http
        port: 9090
        targetPort: 9032
      selector:
        app: upro-application
        subname: interest
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: upro-deployable-route-interest
  namespace: upro-icam-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"  
  labels:
    app: upro-application
    subapp: interest
spec:
  template:
    kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: upro-interest
      namespace: upro-icam-app-ns
      labels:
        app: upro-application
        subname: interest
    spec:
      path: /
      to:
        kind: Service
        name: upro-interest
        weight: 100
      port:
        targetPort: my-http