---
# Source: upro-subscription/templates/11-application.yaml
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: upro-application
  namespace: upro-icam-subscription-ns
  labels:
    app: upro-application
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - upro-application
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
